// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPBAQCDaZmC6hRKNMrvQBIsam9Geji3Q4',
    appId: '1:486948687431:web:7dba6c0c19de0f051ceb62',
    messagingSenderId: '486948687431',
    projectId: 'qrapp-5c399',
    authDomain: 'qrapp-5c399.firebaseapp.com',
    storageBucket: 'qrapp-5c399.appspot.com',
    measurementId: 'G-ZNHDLB1SQB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT3G4n-VCVbQEljRb7QBApB2hLeKW5SNQ',
    appId: '1:486948687431:android:44de4993c6a824501ceb62',
    messagingSenderId: '486948687431',
    projectId: 'qrapp-5c399',
    storageBucket: 'qrapp-5c399.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUXO5VnJy3aeWptS1_EQf25rosYUpjXnw',
    appId: '1:486948687431:ios:fbc4692a97f72aeb1ceb62',
    messagingSenderId: '486948687431',
    projectId: 'qrapp-5c399',
    storageBucket: 'qrapp-5c399.appspot.com',
    iosBundleId: 'com.example.qrApp.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUXO5VnJy3aeWptS1_EQf25rosYUpjXnw',
    appId: '1:486948687431:ios:fbc4692a97f72aeb1ceb62',
    messagingSenderId: '486948687431',
    projectId: 'qrapp-5c399',
    storageBucket: 'qrapp-5c399.appspot.com',
    iosBundleId: 'com.example.qrApp.RunnerTests',
  );
}
